# Generated by Django 3.1.7 on 2021-03-21 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('revealed_date', models.DateTimeField(db_index=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
