# Generated by Django 3.1.7 on 2021-03-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sealedmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
