apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "default"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}
          {{- if .Values.image.tag -}}
            :{{ .Values.image.tag }}
          {{- end }}"
          imagePullPolicy: Always
          env:
            - name: "DB_HOST"
              value: {{ .Values.dbHost }}
            - name: "DB_PASSWORD"
              value: {{ .Values.dbPassword }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
