---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- with .Values.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: "PathPrefix(`/api`, `/static-backend`) || Path(`/readyz`, `/healthz`)"
      kind: Rule
      services:
        - name: {{ include "backend.name" . }}
          port: {{ include "service.port" . }}
