name: "Continuous Integration"
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        command:
          - "black --diff ."
          - "python manage.py test"
    name: "Run checks"
    runs-on:
      ubuntu-20.04
      # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11.11
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: local_password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2

      - name: "Install docker buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Restore docker cache"
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: "Build CI container"
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --load \
            --tag ci \
            --file operations/Dockerfile.backend \
            --target build \
            backend
            
      - name: "Write secrets to disk"
        env:
          FILE_TO_MOUNT: ${{ secrets.FILE_TO_MOUNT }}
        run: |
          echo "${FILE_TO_MOUNT}" > ${HOME}/foo.txt
          cat ${HOME}/foo.txt

      - name: "Execute check"
        env:
          DB_HOST: "localhost"
          DB_PASSWORD: "local_password"
        run: |
          docker run --mount "type=bind,src=${HOME}/foo.txt,dst=/root/foo.txt" \
            --rm ubuntu:20.04 cat /root/foo.txt
          docker run --network host -e DB_HOST -e DB_PASSWORD --rm ci ${{ matrix.command }}

  tilt-ci:
    name: "Run Tilt ci"
    runs-on:
      ubuntu-20.04

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/setup@v1
      - name: Run commands
        run: |
          asdf plugin-add tilt
          asdf install tilt
          tilt ci
