name: "Continuous Integration"
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        command:
          - "black --check backend"
          - "black --check tests"
          - "pytest"
    name: "Run checks"
    runs-on: ubuntu-20.04
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2

      - name: "Install docker buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Restore docker cache"
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: "Execute check"
        run: |
          docker build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --tag ci:${{ github.sha }} \
            --file operations/Dockerfile.backend \
            --target build \
            backend

          docker run --rm ci ${{ matrix.command }}
